### ISSUE TITLE
建议MDUT 新增 ntunnel_mysql.php 做HTTP代理的功能

### ISSUE THREAD

**Issue by coffeehb** [SafeGroceryStore/MDUT#33]
提一个想法，望大佬解答。系统MDUT能够支持类似 navicat 中 使用ntunnel_mysql.php 做HTTP代理的功能
### 新功能描述
    navicat 中 使用ntunnel_mysql.php 做HTTP代理的功能，可以在获得webshell后，不需要自己搭建代理服务下，以一种更隐蔽的方式。访问目标的内网mysql数据库地址.

类似的，ntunnel_mysql.jsp, ntunnel_mysql.aspx，ntunnel_mssql.php, ntunnel_oracle.php 等也可以有

**Comment by Ch1ngg** [comment]
todo 写着了，一直没时间搞这个功能

在 2021年12月8日，10:11，Komi ***@***.***> 写道：

﻿

提一个想法，望大佬解答。系统MDUT能够支持类似 navicat 中 使用ntunnel_mysql.php 做HTTP代理的功能

新功能描述

navicat 中 使用ntunnel_mysql.php 做HTTP代理的功能，可以在获得webshell后，不需要自己搭建代理服务下，以一种更隐蔽的方式。访问目标的内网mysql数据库地址.


类似的，ntunnel_mysql.jsp, ntunnel_mysql.aspx，ntunnel_mssql.php, ntunnel_oracle.php 等也可以有

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSafeGroceryStore%2FMDUT%2Fissues%2F33&data=04%7C01%7C%7C42ef7f5725084b150b9f08d9b9f00f3a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637745262997077346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BXJlr2TurzXXJN%2FX5N5nzJ954H71Wzq4INTVhQXgmjU%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEI6FPN5A2PT4BZTJSUPLD3UP25FNANCNFSM5JSVHSEQ&data=04%7C01%7C%7C42ef7f5725084b150b9f08d9b9f00f3a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637745262997087303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1j7%2B%2FmTttvWO7eGYtQvwHWJNGCl1twGxFjaOxA86GB8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C42ef7f5725084b150b9f08d9b9f00f3a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637745262997087303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BufBunP2j4u5VbAMVTcF7Pes92VYtwpNpD6u6dDcftg%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C42ef7f5725084b150b9f08d9b9f00f3a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637745262997097265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FY72YArYEdW1zTgjjoFRj%2BjmzbReOj3zfgOzH0swaDs%3D&reserved=0>.
