### ISSUE TITLE
oracle连接问题

### ISSUE THREAD

**Issue by FishM4n** [SafeGroceryStore/MDUT#34]
## 系统环境
 - OS: MacOs
 - jdk8

## Bug 详细描述
![image](https://user-images.githubusercontent.com/59049655/145330791-8ca0655a-c8e1-4497-a7ce-d944e920afe1.png)
navicat 选择sysdba就能连上
![image](https://user-images.githubusercontent.com/59049655/145330908-c1bfed51-f522-4cb4-a72a-9b397fb9a7d7.png)

**Comment by Ch1ngg** [comment]
在用户处手动加 as sysdba。eg：admin as sysdba

在 2021年12月9日，11:46，FishM4n ***@***.***> 写道：

﻿

系统环境

  *   OS: MacOs
  *   jdk8

Bug 详细描述

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59049655%2F145330791-8ca0655a-c8e1-4497-a7ce-d944e920afe1.png&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755353182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wWg%2BU9ynug5r%2FVwJCf73x3DuR%2FXYas8rdXv%2B2Gt9uYo%3D&reserved=0>
navicat 选择sysdba就能连上
[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59049655%2F145330908-c1bfed51-f522-4cb4-a72a-9b397fb9a7d7.png&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755363134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wB%2B19UQ%2FjG4iG%2FXM%2FSUbH6ZufwXUo0RY602D%2BjS7iPA%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSafeGroceryStore%2FMDUT%2Fissues%2F34&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755363134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8z%2BoL%2FW2C7UCrtM4ZrxBubrM8ietMCcZHk9wNeiOwMg%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEI6FPOEEKLVRL4XE57M2T3UQARAJANCNFSM5JVM3KEA&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755373089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8LEuJnqz3IOJVdzC9vERu4h6D%2FoVnM4FVf7%2BkWSW3nE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755383045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LsJVACZL6AgCVJBxfw%2FUsqhswNFwUxeP4MD4%2BhCWjic%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce20287d53e9b4619940808d9bac671ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746183755383045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KAGtjLO2vj5SeloK0wjc%2FgQvDEKjWYx29INTLnAijfM%3D&reserved=0>.

**Comment by FishM4n** [comment]
感谢。。。

**Comment by FishM4n** [comment]
good，感谢，解决
